name: Continuous Integration
run-name: Continuous Integration for ${{ (inputs.version && format('v{0}', inputs.version)) || (github.event.pull_request.number && format('PR {0}', github.event.pull_request.number)) || github.ref_name }}

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      - main
      - "!renovate/*"
  workflow_call:
    inputs:
      version:
        description: Version to build
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: Version to build
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: tobysmith568/actions/.github/actions/checkout-pnpm-project@main

      - name: Run Prettier
        run: pnpm exec prettier --check .

      - name: Run ESLint
        run: pnpm exec eslint . --max-warnings 0

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: tobysmith568/actions/.github/actions/checkout-pnpm-project@main

      - name: Set Version
        run: npm version ${{ inputs.version }} --git-tag-version false

      - name: Build
        run: pnpm run build

      - name: Pack
        run: pnpm pack --pack-destination ./builds

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./builds
          retention-days: 1
          if-no-files-found: error

  test:
    name: Unit Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: tobysmith568/actions/.github/actions/checkout-pnpm-project@main

      - name: Unit Test
        run: pnpm exec vitest run

  licenses:
    name: Check Licenses

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: tobysmith568/actions/.github/actions/checkout-pnpm-project@main

      - name: Check Licenses
        run: pnpm exec license-cop

  codeql:
    name: CodeQL

    uses: ./.github/workflows/codeql.yml

    secrets: inherit

    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
